### ISSUE TITLE
"ihmc_valkyrie_control_java_bridge" failing due to "permission"

### ISSUE THREAD

**Issue by rubenalvesbcn** [ihmcrobotics/ihmc-realtime#2]
Hi all,

I'm testing the [Space Robotics Challenge Simulation](https://bitbucket.org/osrf/srcsim) and I'm facing some problems "randomly".

The roslaunch command is: `roslaunch nasa_challenge qual_task2.launch`

If I run the command above directly on the SSH Terminal, it runs without any problems, but if I run through PYTHON PARAMIKO with the same user, and defining the same environment variables, I have the problem below. Does someone knows what is the possible cause of the problem?

[ERROR] [1480960117.076300946, 6.139000000]: java.lang.RuntimeException: Cannot start realtime thread, do you have permission
[ERROR] [1480960117.076767346, 6.139000000]:     at us.ihmc.realtime.RealtimeThread.start(RealtimeThread.java:112)
[ERROR] [1480960117.077017260, 6.139000000]:     at us.ihmc.util.PeriodicRealtimeThreadScheduler.schedule(PeriodicRealtimeThreadScheduler.java:35)
[ERROR] [1480960117.077293331, 6.139000000]:     at us.ihmc.commonWalkingControlModules.controllerAPI.input.ControllerNetworkSubscriber.<init>(ControllerNetworkSubscriber.java:71)
[ERROR] [1480960117.077649754, 6.139000000]:     at us.ihmc.commonWalkingControlModules.highLevelHumanoidControl.factories.MomentumBasedControllerFactory.createControllerNetworkSubscriber(MomentumBasedControllerFactory.java:141)
[ERROR] [1480960117.077963505, 6.139000000]:     at us.ihmc.valkyrieRosControl.ValkyrieRosControlController.createDRCControllerFactory(ValkyrieRosControlController.java:142)
[ERROR] [1480960117.078300340, 6.139000000]:     at us.ihmc.valkyrieRosControl.ValkyrieRosControlController.init(ValkyrieRosControlController.java:253)
[ERROR] [1480960117.078627824, 6.139000000]:     at us.ihmc.rosControl.IHMCRosControlJavaBridge.initFromNative(IHMCRosControlJavaBridge.java:103)
[ERROR] [1480960117.079052559, 6.139000000]: Initializing controller 'ihmc_valkyrie_control_java_bridge' failed

**Comment by dljsjr** [comment]
@rubenalvesbcn The permission problem you're seeing is related to PAM, specifically the PAM module for resource limits (defined in /etc/security/limits.conf). The user and environment might be correct but by default SSH (even regular openssh) has restrictions on how it interacts with PAM modules. SSH remote commands (e.g. no interactive shell) by default don't use PAM so the changes in /etc/security/limits.conf won't be respected by a non-interactive SSH command whether it's being used via Paramiko or not.

I don't know enough about Paramiko to know how to tell you to solve this. I know that with OpenSSH you can make changes in sshd's configuration files to enable PAM for non-interactive command execution.

Our controller requires these resource limits to be available in order to run correctly, so unfortunately we don't intend implement any workarounds. You can take a look at /etc/security/limits.conf and read up on PAM, and hopefully Paramiko provides mechanisms to make this work.
